// Code generated by MockGen. DO NOT EDIT.
// Source: w:\91_proyectos\Z_Trabajo Entrevistas\TopDoctors\internal\domain\patient_ports.go
//
// Generated by this command:
//
//	mockgen -source=w:\91_proyectos\Z_Trabajo Entrevistas\TopDoctors\internal\domain\patient_ports.go -destination=w:\91_proyectos\Z_Trabajo Entrevistas\TopDoctors\internal\mocks\mock_patient_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"
	domain "topdoctors/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockPatientRepository is a mock of PatientRepository interface.
type MockPatientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPatientRepositoryMockRecorder
	isgomock struct{}
}

// MockPatientRepositoryMockRecorder is the mock recorder for MockPatientRepository.
type MockPatientRepositoryMockRecorder struct {
	mock *MockPatientRepository
}

// NewMockPatientRepository creates a new mock instance.
func NewMockPatientRepository(ctrl *gomock.Controller) *MockPatientRepository {
	mock := &MockPatientRepository{ctrl: ctrl}
	mock.recorder = &MockPatientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatientRepository) EXPECT() *MockPatientRepositoryMockRecorder {
	return m.recorder
}

// CreateDiagnosis mocks base method.
func (m *MockPatientRepository) CreateDiagnosis(diagnosis *domain.Diagnosis) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiagnosis", diagnosis)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDiagnosis indicates an expected call of CreateDiagnosis.
func (mr *MockPatientRepositoryMockRecorder) CreateDiagnosis(diagnosis any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiagnosis", reflect.TypeOf((*MockPatientRepository)(nil).CreateDiagnosis), diagnosis)
}

// CreatePatient mocks base method.
func (m *MockPatientRepository) CreatePatient(patient *domain.Patient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePatient", patient)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePatient indicates an expected call of CreatePatient.
func (mr *MockPatientRepositoryMockRecorder) CreatePatient(patient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePatient", reflect.TypeOf((*MockPatientRepository)(nil).CreatePatient), patient)
}

// GetByDiagnosisDateRange mocks base method.
func (m *MockPatientRepository) GetByDiagnosisDateRange(startDate, endDate time.Time) ([]domain.Diagnosis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDiagnosisDateRange", startDate, endDate)
	ret0, _ := ret[0].([]domain.Diagnosis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDiagnosisDateRange indicates an expected call of GetByDiagnosisDateRange.
func (mr *MockPatientRepositoryMockRecorder) GetByDiagnosisDateRange(startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDiagnosisDateRange", reflect.TypeOf((*MockPatientRepository)(nil).GetByDiagnosisDateRange), startDate, endDate)
}

// GetDiagnosisByPatientID mocks base method.
func (m *MockPatientRepository) GetDiagnosisByPatientID(patientID string) ([]domain.Diagnosis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiagnosisByPatientID", patientID)
	ret0, _ := ret[0].([]domain.Diagnosis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiagnosisByPatientID indicates an expected call of GetDiagnosisByPatientID.
func (mr *MockPatientRepositoryMockRecorder) GetDiagnosisByPatientID(patientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiagnosisByPatientID", reflect.TypeOf((*MockPatientRepository)(nil).GetDiagnosisByPatientID), patientID)
}

// GetDiagnosisByPatientName mocks base method.
func (m *MockPatientRepository) GetDiagnosisByPatientName(name string) ([]domain.Diagnosis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiagnosisByPatientName", name)
	ret0, _ := ret[0].([]domain.Diagnosis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiagnosisByPatientName indicates an expected call of GetDiagnosisByPatientName.
func (mr *MockPatientRepositoryMockRecorder) GetDiagnosisByPatientName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiagnosisByPatientName", reflect.TypeOf((*MockPatientRepository)(nil).GetDiagnosisByPatientName), name)
}

// GetPatientByDNI mocks base method.
func (m *MockPatientRepository) GetPatientByDNI(dni string) (*domain.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPatientByDNI", dni)
	ret0, _ := ret[0].(*domain.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPatientByDNI indicates an expected call of GetPatientByDNI.
func (mr *MockPatientRepositoryMockRecorder) GetPatientByDNI(dni any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatientByDNI", reflect.TypeOf((*MockPatientRepository)(nil).GetPatientByDNI), dni)
}

// GetPatientByID mocks base method.
func (m *MockPatientRepository) GetPatientByID(id string) (*domain.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPatientByID", id)
	ret0, _ := ret[0].(*domain.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPatientByID indicates an expected call of GetPatientByID.
func (mr *MockPatientRepositoryMockRecorder) GetPatientByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatientByID", reflect.TypeOf((*MockPatientRepository)(nil).GetPatientByID), id)
}

// SearchDiagnosis mocks base method.
func (m *MockPatientRepository) SearchDiagnosis(patientName *string, dateStart, dateEnd *time.Time) ([]domain.Diagnosis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchDiagnosis", patientName, dateStart, dateEnd)
	ret0, _ := ret[0].([]domain.Diagnosis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDiagnosis indicates an expected call of SearchDiagnosis.
func (mr *MockPatientRepositoryMockRecorder) SearchDiagnosis(patientName, dateStart, dateEnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDiagnosis", reflect.TypeOf((*MockPatientRepository)(nil).SearchDiagnosis), patientName, dateStart, dateEnd)
}

// MockPatientService is a mock of PatientService interface.
type MockPatientService struct {
	ctrl     *gomock.Controller
	recorder *MockPatientServiceMockRecorder
	isgomock struct{}
}

// MockPatientServiceMockRecorder is the mock recorder for MockPatientService.
type MockPatientServiceMockRecorder struct {
	mock *MockPatientService
}

// NewMockPatientService creates a new mock instance.
func NewMockPatientService(ctrl *gomock.Controller) *MockPatientService {
	mock := &MockPatientService{ctrl: ctrl}
	mock.recorder = &MockPatientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatientService) EXPECT() *MockPatientServiceMockRecorder {
	return m.recorder
}

// CreateDiagnosis mocks base method.
func (m *MockPatientService) CreateDiagnosis(diagnosis *domain.Diagnosis) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiagnosis", diagnosis)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDiagnosis indicates an expected call of CreateDiagnosis.
func (mr *MockPatientServiceMockRecorder) CreateDiagnosis(diagnosis any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiagnosis", reflect.TypeOf((*MockPatientService)(nil).CreateDiagnosis), diagnosis)
}

// CreatePatient mocks base method.
func (m *MockPatientService) CreatePatient(patient *domain.Patient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePatient", patient)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePatient indicates an expected call of CreatePatient.
func (mr *MockPatientServiceMockRecorder) CreatePatient(patient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePatient", reflect.TypeOf((*MockPatientService)(nil).CreatePatient), patient)
}

// GetDiagnostics mocks base method.
func (m *MockPatientService) GetDiagnostics(patientName *string, dateStart, dateEnd *time.Time) ([]domain.Diagnosis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiagnostics", patientName, dateStart, dateEnd)
	ret0, _ := ret[0].([]domain.Diagnosis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiagnostics indicates an expected call of GetDiagnostics.
func (mr *MockPatientServiceMockRecorder) GetDiagnostics(patientName, dateStart, dateEnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiagnostics", reflect.TypeOf((*MockPatientService)(nil).GetDiagnostics), patientName, dateStart, dateEnd)
}

// GetPatient mocks base method.
func (m *MockPatientService) GetPatient(dni string) (*domain.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPatient", dni)
	ret0, _ := ret[0].(*domain.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPatient indicates an expected call of GetPatient.
func (mr *MockPatientServiceMockRecorder) GetPatient(dni any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatient", reflect.TypeOf((*MockPatientService)(nil).GetPatient), dni)
}
