// Code generated by MockGen. DO NOT EDIT.
// Source: w:\91_proyectos\Z_Trabajo Entrevistas\TopDoctors\internal\domain\support.go
//
// Generated by this command:
//
//	mockgen -source=w:\91_proyectos\Z_Trabajo Entrevistas\TopDoctors\internal\domain\support.go -destination=w:\91_proyectos\Z_Trabajo Entrevistas\TopDoctors\internal\mocks\mock_support.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	domain "topdoctors/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockSupport is a mock of Support interface.
type MockSupport struct {
	ctrl     *gomock.Controller
	recorder *MockSupportMockRecorder
	isgomock struct{}
}

// MockSupportMockRecorder is the mock recorder for MockSupport.
type MockSupportMockRecorder struct {
	mock *MockSupport
}

// NewMockSupport creates a new mock instance.
func NewMockSupport(ctrl *gomock.Controller) *MockSupport {
	mock := &MockSupport{ctrl: ctrl}
	mock.recorder = &MockSupportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSupport) EXPECT() *MockSupportMockRecorder {
	return m.recorder
}

// CompareHashPassword mocks base method.
func (m *MockSupport) CompareHashPassword(password, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareHashPassword", password, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompareHashPassword indicates an expected call of CompareHashPassword.
func (mr *MockSupportMockRecorder) CompareHashPassword(password, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareHashPassword", reflect.TypeOf((*MockSupport)(nil).CompareHashPassword), password, hash)
}

// CreateNewID mocks base method.
func (m *MockSupport) CreateNewID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNewID indicates an expected call of CreateNewID.
func (mr *MockSupportMockRecorder) CreateNewID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewID", reflect.TypeOf((*MockSupport)(nil).CreateNewID))
}

// GenerateHashPassword mocks base method.
func (m *MockSupport) GenerateHashPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateHashPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateHashPassword indicates an expected call of GenerateHashPassword.
func (mr *MockSupportMockRecorder) GenerateHashPassword(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateHashPassword", reflect.TypeOf((*MockSupport)(nil).GenerateHashPassword), password)
}

// GenerateToken mocks base method.
func (m *MockSupport) GenerateToken(user *domain.User, secret string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", user, secret)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockSupportMockRecorder) GenerateToken(user, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockSupport)(nil).GenerateToken), user, secret)
}

// ValidateToken mocks base method.
func (m *MockSupport) ValidateToken(token, secret string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", token, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockSupportMockRecorder) ValidateToken(token, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockSupport)(nil).ValidateToken), token, secret)
}
