// Code generated by MockGen. DO NOT EDIT.
// Source: topdoctors/internal/core/ports (interfaces: PatientRepository,DiagnosisRepository,UserRepository)
//
// Generated by this command:
//
//	mockgen -destination internal/core/ports/mocks/mocks.go -package mocks topdoctors/internal/core/ports PatientRepository,DiagnosisRepository,UserRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"
	domain "topdoctors/internal/core/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockPatientRepository is a mock of PatientRepository interface.
type MockPatientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPatientRepositoryMockRecorder
	isgomock struct{}
}

// MockPatientRepositoryMockRecorder is the mock recorder for MockPatientRepository.
type MockPatientRepositoryMockRecorder struct {
	mock *MockPatientRepository
}

// NewMockPatientRepository creates a new mock instance.
func NewMockPatientRepository(ctrl *gomock.Controller) *MockPatientRepository {
	mock := &MockPatientRepository{ctrl: ctrl}
	mock.recorder = &MockPatientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatientRepository) EXPECT() *MockPatientRepositoryMockRecorder {
	return m.recorder
}

// CreatePatient mocks base method.
func (m *MockPatientRepository) CreatePatient(patient *domain.Patient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePatient", patient)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePatient indicates an expected call of CreatePatient.
func (mr *MockPatientRepositoryMockRecorder) CreatePatient(patient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePatient", reflect.TypeOf((*MockPatientRepository)(nil).CreatePatient), patient)
}

// GetByDNI mocks base method.
func (m *MockPatientRepository) GetByDNI(dni string) (*domain.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDNI", dni)
	ret0, _ := ret[0].(*domain.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDNI indicates an expected call of GetByDNI.
func (mr *MockPatientRepositoryMockRecorder) GetByDNI(dni any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDNI", reflect.TypeOf((*MockPatientRepository)(nil).GetByDNI), dni)
}

// GetByID mocks base method.
func (m *MockPatientRepository) GetByID(id uint) (*domain.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*domain.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPatientRepositoryMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPatientRepository)(nil).GetByID), id)
}

// MockDiagnosisRepository is a mock of DiagnosisRepository interface.
type MockDiagnosisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDiagnosisRepositoryMockRecorder
	isgomock struct{}
}

// MockDiagnosisRepositoryMockRecorder is the mock recorder for MockDiagnosisRepository.
type MockDiagnosisRepositoryMockRecorder struct {
	mock *MockDiagnosisRepository
}

// NewMockDiagnosisRepository creates a new mock instance.
func NewMockDiagnosisRepository(ctrl *gomock.Controller) *MockDiagnosisRepository {
	mock := &MockDiagnosisRepository{ctrl: ctrl}
	mock.recorder = &MockDiagnosisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiagnosisRepository) EXPECT() *MockDiagnosisRepositoryMockRecorder {
	return m.recorder
}

// CreateDiagnosis mocks base method.
func (m *MockDiagnosisRepository) CreateDiagnosis(diagnosis *domain.Diagnosis) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDiagnosis", diagnosis)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDiagnosis indicates an expected call of CreateDiagnosis.
func (mr *MockDiagnosisRepositoryMockRecorder) CreateDiagnosis(diagnosis any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDiagnosis", reflect.TypeOf((*MockDiagnosisRepository)(nil).CreateDiagnosis), diagnosis)
}

// GetByDateRange mocks base method.
func (m *MockDiagnosisRepository) GetByDateRange(startDate, endDate time.Time) ([]domain.Diagnosis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDateRange", startDate, endDate)
	ret0, _ := ret[0].([]domain.Diagnosis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDateRange indicates an expected call of GetByDateRange.
func (mr *MockDiagnosisRepositoryMockRecorder) GetByDateRange(startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDateRange", reflect.TypeOf((*MockDiagnosisRepository)(nil).GetByDateRange), startDate, endDate)
}

// GetByPatientID mocks base method.
func (m *MockDiagnosisRepository) GetByPatientID(patientID uint) ([]domain.Diagnosis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPatientID", patientID)
	ret0, _ := ret[0].([]domain.Diagnosis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPatientID indicates an expected call of GetByPatientID.
func (mr *MockDiagnosisRepositoryMockRecorder) GetByPatientID(patientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPatientID", reflect.TypeOf((*MockDiagnosisRepository)(nil).GetByPatientID), patientID)
}

// GetByPatientName mocks base method.
func (m *MockDiagnosisRepository) GetByPatientName(name string) ([]domain.Diagnosis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPatientName", name)
	ret0, _ := ret[0].([]domain.Diagnosis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPatientName indicates an expected call of GetByPatientName.
func (mr *MockDiagnosisRepositoryMockRecorder) GetByPatientName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPatientName", reflect.TypeOf((*MockDiagnosisRepository)(nil).GetByPatientName), name)
}

// Search mocks base method.
func (m *MockDiagnosisRepository) Search(patientName string, date *time.Time) ([]domain.Diagnosis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", patientName, date)
	ret0, _ := ret[0].([]domain.Diagnosis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockDiagnosisRepositoryMockRecorder) Search(patientName, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockDiagnosisRepository)(nil).Search), patientName, date)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), user)
}

// GetByUsername mocks base method.
func (m *MockUserRepository) GetByUsername(username string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", username)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserRepositoryMockRecorder) GetByUsername(username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetByUsername), username)
}
